### ISSUE TITLE
Glider keeps moving to pants slot and does not activate

### ISSUE THREAD

**Issue by Luna-Knight** [Patbox/GlideAway#6]
they turn into leather pants as armor but its still the glider in the slot

**Comment by Patbox** [comment]
Hey what version? Did you take it craft the creative ui or did you craft it in survival?

**Comment by Luna-Knight** [comment]
1.21 and I took it out from the creative UI to just test it, does it need to be crafted to function? I did switch to survival but the issue still occurred.
