### ISSUE TITLE
My glider is a box that is purple and black?

### ISSUE THREAD

**Issue by ImJasonLim** [Patbox/GlideAway#8]
![image](https://github.com/user-attachments/assets/65bb64b0-e1d3-4994-ade5-21220788fa49)

**Comment by Patbox** [comment]
You don't have the required server resource pack. See https://polymer.pb4.eu/latest/user/resource-pack-hosting/ for more info about how to set it up

**Comment by ImJasonLim** [comment]
where do i put all the codes

**Comment by ImJasonLim** [comment]
im using aternos
